import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { QueryProvider } from "@/components/providers/query-provider";
import { SiteHeader } from "@/components/domain/site-header";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const siteUrl = "https://project-risk-ai.vercel.app";
const siteName = "Project Risk AI";
const title =
  "Project Risk AI — Monitoramento Preventivo de Riscos de Projeto com IA";
const description =
  "Plataforma que calcula automaticamente a saúde de projetos de TI e usa IA para identificar riscos ainda não cadastrados, com causa e mitigação sugerida.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title,
  description,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title,
    description,
    url: siteUrl,
    type: "website",
    siteName,
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
  // The OG/Twitter images are generated by the `opengraph-image.tsx` and
  // `twitter-image.tsx` file conventions and injected automatically.
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR" className={`${inter.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <QueryProvider>
          <SiteHeader />
          <main className="mx-auto w-full max-w-5xl flex-1 px-6 py-8">{children}</main>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
